export const GroceryItems: string[] = [
  "milk",
  "whole milk",
  "skim milk",
  "eggs",
  "egg",
  "butter",
  "buttr",
  "cheese",
  "cheddar",
  "ched chz",
  "yogurt",
  "yoghurt",
  "bread",
  "white bread",
  "wheat bread",
  "loaf",
  "chicken",
  "chicken breast",
  "chick",
  "chkn brst",
  "ground beef",
  "grnd beef",
  "hamburger",
  "salmon",
  "salmon fillet",
  "bacon",
  "rice",
  "white rice",
  "brown rice",
  "pasta",
  "spaghetti",
  "macaroni",
  "olive oil",
  "oliveoil",
  "oil",
  "canned tomatoes",
  "tomato sauce",
  "tomato",
  "black beans",
  "beans",
  "lentils",
  "potatoes",
  "potato",
  "onions",
  "onion",
  "garlic",
  "bell peppers",
  "pepper",
  "mushrooms",
  "spinach",
  "broccoli",
  "carrots",
  "apples",
  "apple",
  "bananas",
  "banana",
  "oranges",
  "orange",
  "peanut butter",
  "pb",
  "cereal",
  "coffee",
  "ground coffee",
  "coffee beans",
  "grape",
  "grapes",
];

export const NonFoodItems: string[] = [
  "savings",
  "toilet paper",
  "toilet tissue",
  "bath tissue",
  "tp",
  "paper towels",
  "paper towel",
  "ptowel",
  "facial tissues",
  "tissues",
  "napkins",
  "aluminum foil",
  "foil",
  "plastic wrap",
  "cling wrap",
  "saran wrap",
  "parchment paper",
  "trash bags",
  "garbage bags",
  "dish soap",
  "dishwashing liquid",
  "dish liquid",
  "sponges",
  "sponge",
  "dish scrubbers",
  "scrubber",
  "all-purpose cleaner",
  "cleaner",
  "disinfectant wipes",
  "disinfecting wipes",
  "wipes",
  "glass cleaner",
  "window cleaner",
  "bathroom cleaner",
  "bath cleaner",
  "laundry detergent",
  "detergent",
  "laundry soap",
  "fabric softener",
  "softener",
  "dryer sheets",
  "hand soap",
  "soap",
  "hand sanitizer",
  "sanitizer",
  "shampoo",
  "conditioner",
  "body wash",
  "bar soap",
  "toothpaste",
  "toothbrush",
  "toothbrushes",
  "dental floss",
  "deodorant",
  "razors",
  "shaving cream",
  "feminine hygiene products",
  "feminine products",
  "diapers",
  "baby wipes",
  "batteries",
  "battery",
  "light bulbs",
  "light bulb",
  "bulbs",
  "candles",
  "matches",
  "air fresheners",
  "air freshener",
  "greeting cards",
  "aluminum pans",
  "foil pans",
  "plastic food storage bags",
  "storage bags",
  "zip bags",
  "ziploc",
];
