import { FoodInfo } from "../../utils/types";

export const CONDIMENTS: FoodInfo[] = [
  {
    name: "apple butter",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "balsamic vinagrette",
    days_fridge: 212,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "bbq sauce",
    days_fridge: 456,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "blue cheese",
    days_fridge: 456,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "caesar salad dressing",
    days_fridge: 212,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "capers",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "chili sauce",
    days_fridge: 456,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "chutney",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "cocktail sauce",
    days_fridge: 456,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "cooking spray",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "vegetable oil spray",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "dill pickles",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "french salad dressing",
    days_fridge: 212,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "garlic paste",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "gherkin pickles",
    days_fridge: null,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "ginger paste",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "canned gravy",
    days_fridge: 456,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "gravy mix",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "gravy",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 91,
  },
  {
    name: "hoisin sauce",
    days_fridge: 912,
    days_pantry: 912,
    days_freezer: null,
  },
  {
    name: "honey dijon dressing",
    days_fridge: 212,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "horseradish",
    days_fridge: 121,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "hot pepper sauce",
    days_fridge: 1825,
    days_pantry: 1825,
    days_freezer: null,
  },
  {
    name: "italian dressing",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "katsu sauce",
    days_fridge: 705,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "ketchup",
    days_fridge: 335,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "lard",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "margarine",
    days_fridge: 91,
    days_pantry: null,
    days_freezer: 335,
  },
  {
    name: "marinade",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "mayonnaise",
    days_fridge: 76,
    days_pantry: 80,
    days_freezer: null,
  },
  {
    name: "miso",
    days_fridge: 547,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "mustard",
    days_fridge: 456,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "canola oil",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "chili oil",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "oil",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "corn oil",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "vegetable oil",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "olive oil",
    days_fridge: 730,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "oyster saucel",
    days_fridge: 730,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "pasta sauce",
    days_fridge: 9,
    days_pantry: 730,
    days_freezer: 106,
  },
  {
    name: "ragu",
    days_fridge: 9,
    days_pantry: 730,
    days_freezer: 106,
  },
  {
    name: "pesto",
    days_fridge: 15,
    days_pantry: 456,
    days_freezer: 121,
  },
  {
    name: "plum sauce",
    days_fridge: 365,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "duck sauce",
    days_fridge: 365,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "ranch",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "relish",
    days_fridge: 365,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "salad dressing",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "salsa",
    days_fridge: 30,
    days_pantry: 456,
    days_freezer: 60,
  },
  {
    name: "soy sauce",
    days_fridge: 730,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "marinara sauce",
    days_fridge: 12,
    days_pantry: 456,
    days_freezer: 152,
  },
  {
    name: "steak sauce",
    days_fridge: 730,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "stir fry sauce",
    days_fridge: 730,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "sweet sour sauce",
    days_fridge: 365,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "sweet pickles",
    days_fridge: 182,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "tartar sauce",
    days_fridge: 365,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "teriyaki sauce",
    days_fridge: 365,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "thousand island dressing",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "wasabi paste",
    days_fridge: 212,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "worcestershire",
    days_fridge: 1095,
    days_pantry: 1642,
    days_freezer: null,
  },
];
