import { FoodInfo } from "../../app/utils/types";

export const DAIRY: FoodInfo[] = [
  {
    name: "deli sliced american cheese",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 213,
  },
  {
    name: "asiago cheese block",
    days_fridge: 243,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "beaufort cheese block",
    days_fridge: 182,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "blue cheese crumbles",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "blue cheese wedge",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "brie cheese wedge",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "butter",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "buttermilk",
    days_fridge: 14,
    days_pantry: 0,
    days_freezer: 90,
  },

  {
    name: "camebert cheese",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "cheddar cheese sliced",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "cheddar cheese block",
    days_fridge: 182,
    days_pantry: null,
    days_freezer: 243,
  },

  {
    name: "cheese soup",
    days_fridge: 1826,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cheshire cheese",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "chocolate milk",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "colby cheese block",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "colby cheese sliced",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "cottage cheese",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "cream cheese block",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 60,
  },

  {
    name: "cream fluid",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "creme fraiche",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "custard",
    days_fridge: 6,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "derby cheese",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "whipped cream",
    days_fridge: 90,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "dubliner cheese",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "edam sliced cheese",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "edam cheese block",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "egg salad",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "egg substitute liquid",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "egg whites raw",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "egg yolks raw",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "eggnog commercial",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "hardboiled eggs",
    days_fridge: 7,

    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "eggs",
    days_fridge: 35,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "emmental cheese block",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "farmer cheese",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "feta cheese crumbles",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "feta cheese wedge",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "fontina cheese block",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "gloucester cheese block ",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "goat cheese",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "goat cheese crumbles",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "gorgonzola cheese wedge",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "gouda cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "gruyere cheese  slice",
    days_fridge: 13,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "half-and-half",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "harvarti cheese slice",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "harvarti cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "heavy cream",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "jarlsberg cheese slice",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "jarlsberg cheese block",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "light cream",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "limburger cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "mascarpone cheese",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "evaporated milk",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "lactose free milk",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "milk",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "milk sweetened condensed",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "monterey jack cheese sliced",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "monterey jack cheese block",
    days_fridge: 182,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "mozzarella cheese slice",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "muenster cheese commercial slice",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "muenster cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "neufchatel cheese",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "powdered creamer",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "non-dairy creamer liquid",
    days_fridge: 17,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "parmesan cheese grated",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "parmesan cheese block",
    days_fridge: 243,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "parmigiano-reggiano cheese block",
    days_fridge: 365,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "powdered milk ",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: 1095,
  },
  {
    name: "provolone cheese sliced",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "provolone cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "ricotta cheese",
    days_fridge: 15,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "romano cheese block",
    days_fridge: 243,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "roquefort cheese wedge",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "sour cream",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "silton cheese wedge",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "string cheese",
    days_fridge: 28,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "swiss cheese deli sliced",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "swiss cheese block",
    days_fridge: 182,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "tilsiter cheese block",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "frozen yogurt",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "yogurt",
    days_fridge: 25,
    days_pantry: null,
    days_freezer: 60,
  },
];
