import { FoodInfo } from "../../app/utils/types";

export const FISH: FoodInfo[] = [
  {
    name: "canned anchovy",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "frozen calamari",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "catfish",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "caviar",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "clam chowder",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "clam",
    days_fridge: 2,
    days_pantry: 1460,
    days_freezer: 106,
  },
  {
    name: "cod",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "crab",
    days_fridge: 2,
    days_pantry: 1460,
    days_freezer: 212,
  },
  {
    name: "escargot",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 152,
  },
  {
    name: "fish stick",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "fish stock",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "flounder",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "frog",
    days_fridge: 1,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "seafood dinner",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "grouper",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "haddock",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "halibut",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "lobster meat",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "lox",
    days_fridge: 18,
    days_pantry: null,
    days_freezer: 76,
  },
  {
    name: "mackrel",
    days_fridge: 2,
    days_pantry: 1460,
    days_freezer: 212,
  },
  {
    name: "mahi mahi",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "monkfish",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 305,
  },
  {
    name: "mullet",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 76,
  },
  {
    name: "mussel",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 200,
  },
  {
    name: "octopus",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "oyster",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "salmon",
    days_fridge: 2,
    days_pantry: 1460,
    days_freezer: 76,
  },
  {
    name: "salmon roe",
    days_fridge: 25,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "sardines",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "scallop",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "sea bass",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "shrimp",
    days_fridge: 2,
    days_pantry: 1406,
    days_freezer: 273,
  },
  {
    name: "skate",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "squid",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "calamari",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "sushi",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "tilapia",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "trout",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "tuna",
    days_fridge: 2,
    days_pantry: 1460,
    days_freezer: 273,
  },
  {
    name: "tuna salad",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "turbot",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 212,
  },
  {
    name: "whitefish",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 76,
  },
];
