import { FoodInfo } from "../../app/utils/types";

export const FRUITS: FoodInfo[] = [
  {
    name: "juice",
    days_fridge: 20,
    days_pantry: 608,
    days_freezer: 365,
  },
  {
    name: "apple",
    days_fridge: 30,
    days_pantry: 6,
    days_freezer: 365,
  },
  {
    name: "applesauce",
    days_fridge: null,
    days_pantry: 425,
    days_freezer: 30,
  },
  {
    name: "apricot nectar",
    days_fridge: null,
    days_pantry: 425,
    days_freezer: 304,
  },
  {
    name: "apricot",
    days_fridge: 6,
    days_pantry: 3,
    days_freezer: 273,
  },
  {
    name: "avocado",
    days_fridge: 7,
    days_pantry: 5,
    days_freezer: 152,
  },
  {
    name: "banana",
    days_fridge: 9,
    days_pantry: 4,
    days_freezer: 61,
  },
  {
    name: "dried banana",
    days_fridge: 304,
    days_pantry: 304,
    days_freezer: 456,
  },
  {
    name: "blackberry",
    days_fridge: 3,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "blueberry",
    days_fridge: 12,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "frozen blueberry",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cantaloupe",
    days_fridge: 4,
    days_pantry: 2,
    days_freezer: 273,
  },
  {
    name: "cherry",
    days_fridge: 8,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "clementine",
    days_fridge: 12,
    days_pantry: 7,
    days_freezer: 273,
  },
  {
    name: "dried cranberry",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "canned fruit cocktail",
    days_fridge: 608,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "fruit punch",
    days_fridge: null,
    days_pantry: 20,
    days_freezer: 273,
  },
  {
    name: "gooseberry",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "cranberry sauce",
    days_fridge: 608,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "currant",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 335,
  },
  {
    name: "dried currant",
    days_fridge: 335,
    days_pantry: 335,
    days_freezer: 456,
  },
  {
    name: "date",
    days_fridge: 365,
    days_pantry: 45,
    days_freezer: 547,
  },
  {
    name: "prunes",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "elderberry",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 456,
  },
  {
    name: "fig",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 456,
  },
  {
    name: "dried fig",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "grapefruit",
    days_fridge: 25,
    days_pantry: 7,
    days_freezer: 335,
  },
  {
    name: "grape",
    days_fridge: 11,
    days_pantry: 2,
    days_freezer: 335,
  },
  {
    name: "guanabana nectar",
    days_fridge: null,
    days_pantry: 456,
    days_freezer: 273,
  },
  {
    name: "guava",
    days_fridge: 7,
    days_pantry: 8,
    days_freezer: 335,
  },
  {
    name: "guava nectar",
    days_fridge: null,
    days_pantry: 456,
    days_freezer: 273,
  },
  {
    name: "honeydew",
    days_fridge: 6,
    days_pantry: 4,
    days_freezer: 273,
  },
  {
    name: "huckleberry",
    days_fridge: 13,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "lemon juice",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "lemonade",
    days_fridge: 30,
    days_pantry: 30,
    days_freezer: 456,
  },
  {
    name: "lemon",
    days_fridge: 25,
    days_pantry: 7,
    days_freezer: 121,
  },
  {
    name: "lime juice",
    days_fridge: 243,
    days_pantry: 456,
    days_freezer: null,
  },
  {
    name: "lime",
    days_fridge: 25,
    days_pantry: 7,
    days_freezer: 121,
  },
  {
    name: "lychee",
    days_fridge: 6,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "dried lychee",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "dried jujubes",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "kiwi",
    days_fridge: 21,
    days_pantry: 5,
    days_freezer: 334,
  },
  {
    name: "dried kiwi",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "kumquat",
    days_fridge: 18,
    days_pantry: 4,
    days_freezer: 335,
  },
  {
    name: "canned olive",
    days_fridge: null,
    days_pantry: 912,
    days_freezer: null,
  },
  {
    name: "dried mango",
    days_fridge: 335,
    days_pantry: 335,
    days_freezer: 456,
  },
  {
    name: "mango",
    days_fridge: 5,
    days_pantry: 9,
    days_freezer: 456,
  },
  {
    name: "maraschino cherries",
    days_fridge: null,
    days_pantry: 912,
    days_freezer: null,
  },
  {
    name: "mixed berries",
    days_fridge: 5,
    days_pantry: 1,
    days_freezer: 356,
  },
  {
    name: "nectarine",
    days_fridge: 7,
    days_pantry: 4,
    days_freezer: 335,
  },
  {
    name: "orange",
    days_fridge: 25,
    days_pantry: 6,
    days_freezer: 335,
  },
  {
    name: "papaya",
    days_fridge: 9,
    days_pantry: 5,
    days_freezer: 335,
  },
  {
    name: "passion fruit",
    days_fridge: 9,
    days_pantry: 6,
    days_freezer: 213,
  },
  {
    name: "peach",
    days_fridge: 7,
    days_pantry: 4,
    days_freezer: 365,
  },
  {
    name: "canned peach",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "pear",
    days_fridge: 9,
    days_pantry: 6,
    days_freezer: 335,
  },
  {
    name: "canned pear",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "persimmon",
    days_fridge: 5,
    days_pantry: 4,
    days_freezer: 335,
  },
  {
    name: "dried persimmon",
    days_fridge: 335,
    days_pantry: 335,
    days_freezer: 638,
  },
  {
    name: "plantain",
    days_fridge: 9,
    days_pantry: 6,
    days_freezer: 335,
  },
  {
    name: "plum",
    days_fridge: 6,
    days_pantry: 4,
    days_freezer: 335,
  },
  {
    name: "prune",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 45,
  },
  {
    name: "canned pineapple",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "pineapple",
    days_fridge: 6,
    days_pantry: 5,
    days_freezer: 365,
  },
  {
    name: "quinces",
    days_fridge: 21,
    days_pantry: 6,
    days_freezer: 335,
  },
  {
    name: "rasin",
    days_fridge: 335,
    days_pantry: 335,
    days_freezer: 456,
  },
  {
    name: "raspberry",
    days_fridge: 4,
    days_pantry: 2,
    days_freezer: 365,
  },
  {
    name: "star fruit",
    days_fridge: 8,
    days_pantry: 5,
    days_freezer: 335,
  },
  {
    name: "strawberry",
    days_fridge: 7,
    days_pantry: 2,
    days_freezer: 365,
  },
  {
    name: "tangerine",
    days_fridge: 11,
    days_pantry: 9,
    days_freezer: 335,
  },
  {
    name: "mandarin orange",
    days_fridge: 11,
    days_pantry: 9,
    days_freezer: 335,
  },
  {
    name: "ugli fruit",
    days_fridge: 11,
    days_pantry: 9,
    days_freezer: 335,
  },
  {
    name: "watermelon",
    days_fridge: 14,
    days_pantry: 10,
    days_freezer: 335,
  },
];
