import { FoodInfo } from "../../utils/types";

export const MEATS: FoodInfo[] = [
  {
    name: "abruzzese sausage dry",
    days_fridge: 182,
    days_pantry: 42,
    days_freezer: 304,
  },
  {
    name: "imitation bacon bits",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "bacon raw wrapped",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },

  {
    name: "beef brisket",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "broth",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "frozen burgers",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "beef entrees frozen",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "beef jerky",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },

  {
    name: "beef ribs",

    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "roast beef",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "beef soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "steak",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "ground beef",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "blood sausage",
    days_fridge: 25,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "bologna packaged",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "bratwurst",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "breakfast sausage",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "sausage links",
    days_fridge: 9,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "stock",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "sliced chicken",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "chicken entrees",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "chicken nuggets ",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "chicken pot pie",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "chicken strips",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "chicken wings",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "chicken ground",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "whole chicken",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "barbequed spare ribs",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "beef chop suey",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "beef chow mein",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "beef with broccoli",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "chicken chop suey",

    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "chicken chow mein",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "chicken lo mein",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "egg rolls",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "general tsos chicken",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "pork chop suey",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "pork chop mein",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "pork lo mein",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "sweet and sour chicken",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },

  {
    name: "sweet and sour pork",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "wonton soup",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "chorizo",
    days_fridge: 42,
    days_pantry: 182,
    days_freezer: 304,
  },
  {
    name: "corned beef hash",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "country ham",
    days_fridge: 90,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cream of chicken soup",

    days_fridge: null,
    days_pantry: null,
    days_freezer: 1826,
  },
  {
    name: "dry sausage packaged",
    days_fridge: 182,
    days_pantry: 42,
    days_freezer: 304,
  },
  {
    name: "duck",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "giblets",
    days_fridge: 2,
    days_pantry: null,

    days_freezer: 121,
  },
  {
    name: "goose",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "sliced ham",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "hot dogs",
    days_fridge: 15,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "italian sausage",

    days_fridge: 2,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "knockwurst",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "lamb chops",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "lamb entree",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "kidney",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "liver",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "ribs",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "ground lamb",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "liverwurst ",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "pancetta",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "pastrami",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "pate",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "pepperoni",
    days_fridge: 182,
    days_pantry: 42,
    days_freezer: 304,
  },
  {
    name: "kielbasa",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "pork chops",

    days_fridge: 5,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "pork entrees",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "ground pork",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "rabbit",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "sliced roast beef",

    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "salami",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },

  {
    name: "salt pork",
    days_fridge: 30,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "raw sausage",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "summer sausage",
    days_fridge: 90,
    days_pantry: 42,
    days_freezer: 200,
  },
  {
    name: "sliced turkey",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "turkey entree",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "ground turkey",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "whole turkey",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "veal chops",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "ground veal",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "venison",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 273,
  },
];
