import { FoodInfo } from "../../utils/types";

export const NUTS_PASTA: FoodInfo[] = [
  {
    name: "almond",
    days_fridge: 365,
    days_pantry: 456,
    days_freezer: 730,
  },
  {
    name: "pasta",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "spaghetti",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "orizo",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "pasta shells",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "linguini",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "ziti",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "vermicelli",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "penne",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "mancotti",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "angel hair",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "macaroni",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "fettuccine",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "rigatoni",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "rotini",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "bow tie",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "noodle",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: null,
  },
  {
    name: "egg noodle",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "baked beans",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "barley",
    days_fridge: null,
    days_pantry: 608,
    days_freezer: null,
  },
  {
    name: "black eyed peas",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "brazil nuts",
    days_fridge: 365,
    days_pantry: 35,
    days_freezer: 456,
  },
  {
    name: "cereal",
    days_fridge: null,
    days_pantry: 65,
    days_freezer: null,
  },
  {
    name: "chestnut",
    days_fridge: 5,
    days_pantry: 7,
    days_freezer: 310,
  },
  {
    name: "chickpea",
    days_fridge: 5,
    days_pantry: 200,
    days_freezer: 182,
  },
  {
    name: "garbonzo bean",
    days_fridge: null,
    days_pantry: 912,
    days_freezer: 182,
  },
  {
    name: "canned chickpea",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "canned coconut milk",
    days_fridge: null,
    days_pantry: 1277,
    days_freezer: null,
  },
  {
    name: "coconut",
    days_fridge: 30,
    days_pantry: 7,
    days_freezer: null,
  },
  {
    name: "cornmeal",
    days_fridge: 76,
    days_pantry: 30,
    days_freezer: 152,
  },
  {
    name: "cornstarch",
    days_fridge: null,
    days_pantry: -1, // Means indefinite
    days_freezer: null,
  },
  {
    name: "beans",
    days_fridge: null,
    days_pantry: 912,
    days_freezer: null,
  },
  {
    name: "farina",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "grits",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "hazelnut",
    days_fridge: 273,
    days_pantry: 91,
    days_freezer: 365,
  },
  {
    name: "kidney bean",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "lasagna",
    days_fridge: null,
    days_pantry: 1095,
    days_freezer: 547,
  },
  {
    name: "lentil soup",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "lentils",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "lima beans",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "macadamia nuts",
    days_fridge: 182,
    days_pantry: 25,
    days_freezer: 304,
  },
  {
    name: "mac n cheese",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 547,
  },
  {
    name: "millet",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "mixed nuts",
    days_fridge: null,
    days_pantry: 335,
    days_freezer: null,
  },
  {
    name: "nuts",
    days_fridge: null,
    days_pantry: 335,
    days_freezer: null,
  },
  {
    name: "oatmeal",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "instant oatmeal",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "oats",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "peanut butter",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "peanuts",
    days_fridge: 152,
    days_pantry: 40,
    days_freezer: 304,
  },
  {
    name: "pecans",
    days_fridge: 365,
    days_pantry: 25,
    days_freezer: 730,
  },
  {
    name: "pinto bean",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "pistachio",
    days_fridge: 91,
    days_pantry: 14,
    days_freezer: 365,
  },
  {
    name: "pumpkin seed",
    days_fridge: 365,
    days_pantry: 91,
    days_freezer: 365,
  },
  {
    name: "quinoa",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "canned ravioli",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "chef boyardee",
    days_fridge: null,
    days_pantry: 638,
    days_freezer: null,
  },
  {
    name: "refried beans",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "basatami rice",
    days_fridge: -1, // indefinite
    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "jasmine rice",
    days_fridge: -1, // indefinite
    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "white rice",
    days_fridge: -1, // indefinite
    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "wild rice",
    days_fridge: -1, // indefinite
    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "rice rice",
    days_fridge: -1, // indefinite
    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "brown rice",
    days_fridge: 273,
    days_pantry: 152,
    days_freezer: 456,
  },
  {
    name: "soybean",
    days_fridge: null,
    days_pantry: 912,
    days_freezer: null,
  },
  {
    name: "split pea",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
  {
    name: "sunflower seeds",
    days_fridge: 365,
    days_pantry: 76,
    days_freezer: 365,
  },
  {
    name: "tapioca",
    days_fridge: null,
    days_pantry: 356,
    days_freezer: null,
  },
  {
    name: "tempeh",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 335,
  },
  {
    name: "tofu",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 152,
  },
  {
    name: "tortellini",
    days_fridge: 7,
    days_pantry: 912,
    days_freezer: 60,
  },
  {
    name: "walnut",
    days_fridge: 335,
    days_pantry: 25,
    days_freezer: 365,
  },
  {
    name: "white bean",
    days_fridge: null,
    days_pantry: 1460,
    days_freezer: null,
  },
];
