import { FoodInfo } from "../../utils/types";

export const SNACKS: FoodInfo[] = [
  {
    name: "apple jelly",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "apple pie",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "apricot jam",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "pie",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "apricot preserves",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "bagels",
    days_fridge: 5,
    days_pantry: 7,
    days_freezer: 365,
  },
  {
    name: "baking powder",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "baking soda",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "banana bread",
    days_fridge: 7,
    days_pantry: 2,
    days_freezer: 90,
  },
  {
    name: "biscuit mix",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "baking mix",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "bisquick",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "biscuit dough",
    days_fridge: 60,

    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "blackberry jam",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "blueberry pie unbaked",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 120,
  },
  {
    name: "blueberry preserves",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "breadcrumbs",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "breadsticks",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: 90,
  },
  {
    name: "brownie mix",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "cake mix",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "frozen cake",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "candy canes",
    days_fridge: 365,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "candy corn",
    days_fridge: 243,
    days_pantry: 243,
    days_freezer: 365,
  },
  {
    name: "caramel",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 365,
  },
  {
    name: "cake",
    days_fridge: 7,
    days_pantry: 2,
    days_freezer: 182,
  },
  {
    name: "cheetos",
    days_fridge: null,
    days_pantry: 60,
    days_freezer: null,
  },
  {
    name: "cheesecake",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "milk chocolate",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "dark chocolate",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 730,
  },
  {
    name: "baking chocolate",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 730,
  },
  {
    name: "bittersweet chocolate",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 730,
  },
  {
    name: "semi-sweet chocolate",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 730,
  },
  {
    name: "chocolate chips",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "chocolate syrup",
    days_fridge: 547,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "hersheys syrup",
    days_fridge: 547,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "chocolate candy",
    days_fridge: 365,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "ciabatta bread ",
    days_fridge: null,
    days_pantry: 3,
    days_freezer: 90,
  },
  {
    name: "cinnamon rolls",
    days_fridge: 10,
    days_pantry: 2,
    days_freezer: 90,
  },
  {
    name: "coffee cake",
    days_fridge: 7,
    days_pantry: 10,
    days_freezer: 90,
  },
  {
    name: "cookie dough",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cookie",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: 365,
  },
  {
    name: "corn bread mix",
    days_fridge: null,
    days_pantry: 35,
    days_freezer: 90,
  },
  {
    name: "corn chips",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "dorito",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "tostito",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "ruffle",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "pringle",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "lays",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "crackers",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: null,
  },
  {
    name: "croissants",
    days_fridge: 7,
    days_pantry: 2,
    days_freezer: 60,
  },
  {
    name: "croutons",
    days_fridge: null,
    days_pantry: 304,
    days_freezer: 365,
  },
  {
    name: "dinner rolls",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "english muffins",
    days_fridge: null,
    days_pantry: 14,
    days_freezer: 90,
  },
  {
    name: "white flour",
    days_fridge: 730,
    days_pantry: 365,
    days_freezer: 730,
  },
  {
    name: "all purpose flour",
    days_fridge: 730,
    days_pantry: 365,
    days_freezer: 730,
  },
  {
    name: "whole wheat flour",
    days_fridge: 243,
    days_pantry: 90,
    days_freezer: 365,
  },
  {
    name: "frosting",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "frozen garlic bread",
    days_fridge: null,
    days_pantry: 1,
    days_freezer: 90,
  },
  {
    name: "granola bar",
    days_fridge: null,
    days_pantry: 243,
    days_freezer: null,
  },
  {
    name: "graham crackers",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: null,
  },
  {
    name: "jam",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "jelly",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "grape jelly",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "guacamole",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "gummi candy",
    days_fridge: 243,
    days_pantry: 243,
    days_freezer: 365,
  },
  {
    name: "hamburger buns",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "hard candy",
    days_fridge: 365,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "hot dog rolls",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "hummus packaged",
    days_fridge: 10,

    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "ice cream bar",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "ice cream sandwich",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "ice cream cone",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "ice cream",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "licorice",
    days_fridge: 243,
    days_pantry: 243,
    days_freezer: 365,
  },
  {
    name: "whoppers",
    days_fridge: 304,
    days_pantry: 304,
    days_freezer: 365,
  },
  {
    name: "syrup",
    days_fridge: null,

    days_pantry: -1,
    days_freezer: -1,
  },
  {
    name: "marmalade",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "marshmallow creme",
    days_fridge: null,
    days_pantry: 121,
    days_freezer: null,
  },
  {
    name: "molasses",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "muffin mix",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "muffins",
    days_fridge: 7,
    days_pantry: 2,
    days_freezer: 90,
  },
  {
    name: "multi grain bread",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "pancake mix",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "waffle mix",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "frozen pancakes",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "reeses",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 365,
  },
  {
    name: "pita bread",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "pizza",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "popcorn",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "popsicle",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "pork rinds",
    days_fridge: null,
    days_pantry: 90,
    days_freezer: null,
  },
  {
    name: "pretzels",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: null,
  },
  {
    name: "protein bars",
    days_fridge: null,
    days_pantry: 40,
    days_freezer: null,
  },
  {
    name: "pudding mix",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "jello",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "quiche",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "rice cake",
    days_fridge: null,
    days_pantry: 182,
    days_freezer: null,
  },
  {
    name: "rye",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "rye rolls",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "snack bar",
    days_fridge: null,
    days_pantry: 243,
    days_freezer: null,
  },
  {
    name: "snack cakes",
    days_fridge: null,
    days_pantry: 60,
    days_freezer: 182,
  },
  {
    name: "sorbet",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "sourdough rolls",
    days_fridge: null,
    days_pantry: 3,
    days_freezer: 90,
  },
  {
    name: "strawberry jam",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "strawberry jelly",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "stuffing mix",
    days_fridge: null,
    days_pantry: 537,
    days_freezer: null,
  },
  {
    name: "brown sugar",
    days_fridge: null,
    days_pantry: -1,
    days_freezer: null,
  },
  {
    name: "white sugar",
    days_fridge: null,
    days_pantry: -1,
    days_freezer: null,
  },
  {
    name: "taco shells",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "poptart",
    days_fridge: null,
    days_pantry: 182,
    days_freezer: null,
  },
  {
    name: "frozen waffles",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "ego",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 121,
  },
  {
    name: "white bread",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "white chocolate",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: 365,
  },
  {
    name: "whole wheat bread",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
  {
    name: "whole wheat rolls",
    days_fridge: null,
    days_pantry: 7,
    days_freezer: 90,
  },
];
