import { FoodInfo } from "../../utils/types";

export const VEGETABLES: FoodInfo[] = [
  {
    name: "alfalfa",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "artichoke",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "arugala",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "asparagus",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned asparagu",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "baby carrot",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "bamboo shoot",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "canned bamboo shoot",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "banana pepper",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "string bean",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "beet",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "canned beet",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "bell pepper",
    days_fridge: 14,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "green bell pepper",
    days_fridge: 14,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "red bell pepper",
    days_fridge: 14,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "yellow bell pepper",
    days_fridge: 14,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "orange bell pepper",
    days_fridge: 14,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "bitter melon",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "bok choy",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "broccoli",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "brussels sprout",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cabbage",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "carrot juice",
    days_fridge: 20,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "carrot unpeele",
    days_fridge: 28,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cauliflower",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "celery",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "chicory",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "chili pepper",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned chili pepper",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "dried chili pepper",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "chop suey",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "chow mein",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "canned chipotle pepper",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "coleslaw",
    days_fridge: 5,

    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "collard greens",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "corn",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "canned corn",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of asparagus soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of broccoli soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of celery soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of mushroom soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of onion soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cream of potato soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "cucumber",
    days_fridge: 2,

    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "dried vegetables",
    days_fridge: null,
    days_pantry: 365,
    days_freezer: null,
  },
  {
    name: "frozen edamame",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "eggplant",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "escarole",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "fennel bulb",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "french onion soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "garlic",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "ginger root",
    days_fridge: 42,
    days_pantry: null,
    days_freezer: 90,
  },
  {
    name: "green beans",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "canned green beans",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "green onion",
    days_fridge: 10,

    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "habanero pepper",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "horseradish root",
    days_fridge: 60,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "jalapeno pepper",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned jalapeno pepper",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "kale",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "bagged kale",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "kohlrabi",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "leeks",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "lettuce",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "bagged lettuce",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "romaine lettuce",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "frozen vegetables",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned vegetables",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "mushroom",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned mushroom",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "okra",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned onion",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "onion",
    days_fridge: 90,
    days_pantry: 90,
    days_freezer: 243,
  },
  {
    name: "parsnip",
    days_fridge: 28,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "peas",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 547,
  },
  {
    name: "canned peas",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "canned beets",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "poblano pepper",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "potato salad",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "potato",
    days_fridge: 30,
    days_pantry: 60,
    days_freezer: 365,
  },
  {
    name: "instant potatoes",
    days_fridge: null,

    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "pumpkin",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned pumpkin",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "radicchio",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "radish",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "rhubarb",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "rutabaga",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 304,
  },
  {
    name: "sauerkraut",
    days_fridge: 182,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "canned sauerkraut",
    days_fridge: 7,
    days_pantry: null,
    days_freezer: 60,
  },
  {
    name: "serrano pepper",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "shallots",
    days_fridge: 10,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "snow pea",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "squash",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "sugar snap pea",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "sweet onion",
    days_fridge: 60,
    days_pantry: 60,
    days_freezer: 365,
  },
  {
    name: "sweet potato",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "swiss chard",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "tomatillo",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "tomato juice",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "tomato paste",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: 1095,
  },
  {
    name: "tomato puree",
    days_fridge: null,
    days_pantry: 547,
    days_freezer: null,
  },
  {
    name: "tomato sauce",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "tomato soup",
    days_fridge: 4,
    days_pantry: null,
    days_freezer: 182,
  },
  {
    name: "tomato",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "canned tomato",
    days_fridge: null,
    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "sundried tomato",
    days_fridge: null,
    days_pantry: 273,
    days_freezer: null,
  },
  {
    name: "truffles",
    days_fridge: 14,
    days_pantry: null,
    days_freezer: 243,
  },
  {
    name: "turnip greens",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "turnip",
    days_fridge: 21,
    days_pantry: null,
    days_freezer: 304,
  },
  {
    name: "vegetable stock",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: 1826,
  },
  {
    name: "vegetable juice",
    days_fridge: null,

    days_pantry: 730,
    days_freezer: null,
  },
  {
    name: "vegetable soup",
    days_fridge: null,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "water chestnut",
    days_fridge: 10,
    days_pantry: 1826,
    days_freezer: null,
  },
  {
    name: "watercress",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "yam",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "zucchini",
    days_fridge: 5,
    days_pantry: null,
    days_freezer: 365,
  },
];
