// Just the raw info
export const FOOD_INFO_DATA = [
  {
    name: "juice",
    days_fridge: 20,
    days_pantry: 608,
    days_freezer: 365,
  },
  {
    name: "apple",
    days_fridge: 30,
    days_pantry: 6,
    days_freezer: 365,
  },
  {
    name: "applesauce",
    days_fridge: null,
    days_pantry: 425,
    days_freezer: 30,
  },
  {
    name: "apricot nectar",
    days_fridge: null,
    days_pantry: 425,
    days_freezer: 304,
  },
  {
    name: "apricot",
    days_fridge: 6,
    days_pantry: 3,
    days_freezer: 273,
  },
  {
    name: "avocado",
    days_fridge: 7,
    days_pantry: 5,
    days_freezer: 152,
  },
  {
    name: "banana",
    days_fridge: 9,
    days_pantry: 4,
    days_freezer: 61,
  },
  {
    name: "dried banana",
    days_fridge: 304,
    days_pantry: 304,
    days_freezer: 456,
  },
  {
    name: "blackberry",
    days_fridge: 3,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "blueberry",
    days_fridge: 12,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "frozen blueberry",
    days_fridge: null,
    days_pantry: null,
    days_freezer: 365,
  },
  {
    name: "cantaloupe",
    days_fridge: 4,
    days_pantry: 2,
    days_freezer: 273,
  },
  {
    name: "cherry",
    days_fridge: 8,
    days_pantry: 1,
    days_freezer: 273,
  },
  {
    name: "clementine",
    days_fridge: 12,
    days_pantry: 7,
    days_freezer: 273,
  },
  {
    name: "dried cranberry",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "canned fruit cocktail",
    days_fridge: 608,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "fruit punch",
    days_fridge: null,
    days_pantry: 20,
    days_freezer: 273,
  },
  {
    name: "gooseberry",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 273,
  },
  {
    name: "cranberry sauce",
    days_fridge: 608,
    days_pantry: null,
    days_freezer: null,
  },
  {
    name: "currant",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 335,
  },
  {
    name: "dried currant",
    days_fridge: 335,
    days_pantry: 335,
    days_freezer: 456,
  },
  {
    name: "date",
    days_fridge: 365,
    days_pantry: 45,
    days_freezer: 547,
  },
  {
    name: "prunes",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
  {
    name: "elderberry",
    days_fridge: 3,
    days_pantry: null,
    days_freezer: 456,
  },
  {
    name: "fig",
    days_fridge: 2,
    days_pantry: null,
    days_freezer: 456,
  },
  {
    name: "dried fig",
    days_fridge: 273,
    days_pantry: 273,
    days_freezer: 456,
  },
];
// Done: Fruites pages 1-3
