export const NonFoodItems: string[] = [
  "savings",
  "toilet paper",
  "toilet tissue",
  "bath tissue",
  "tp",
  "paper towels",
  "paper towel",
  "ptowel",
  "facial tissues",
  "tissues",
  "napkins",
  "aluminum foil",
  "foil",
  "plastic wrap",
  "cling wrap",
  "saran wrap",
  "parchment paper",
  "trash bags",
  "garbage bags",
  "dish soap",
  "dishwashing liquid",
  "dish liquid",
  "sponges",
  "sponge",
  "dish scrubbers",
  "scrubber",
  "all-purpose cleaner",
  "cleaner",
  "disinfectant wipes",
  "disinfecting wipes",
  "wipes",
  "glass cleaner",
  "window cleaner",
  "bathroom cleaner",
  "bath cleaner",
  "laundry detergent",
  "detergent",
  "laundry soap",
  "fabric softener",
  "softener",
  "dryer sheets",
  "hand soap",
  "soap",
  "hand sanitizer",
  "sanitizer",
  "shampoo",
  "conditioner",
  "body wash",
  "bar soap",
  "toothpaste",
  "toothbrush",
  "toothbrushes",
  "dental floss",
  "deodorant",
  "razors",
  "shaving cream",
  "feminine hygiene products",
  "feminine products",
  "diapers",
  "baby wipes",
  "batteries",
  "battery",
  "light bulbs",
  "light bulb",
  "bulbs",
  "candles",
  "matches",
  "air fresheners",
  "air freshener",
  "greeting cards",
  "aluminum pans",
  "foil pans",
  "plastic food storage bags",
  "storage bags",
  "zip bags",
  "ziploc",
];
